baseURL = 'https://gyshsedu.com/'
title = 'Guanyun Senior High School'
languageCode = "en-us"
defaultContentLanguage = "en"
# title = '灌云高级中学'
theme = 'universal'
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true

[languages]
[languages.en]
languageCode = 'en-us'
languageName = 'English - United States'
weight = 1
[languages.cn]
languageCode = 'zh-cn'
languageName = '简体中文'
weight = 2
[languages.tw]
languageCode = 'zh-tw'
languageName = '正體中文'
weight = 3
